name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun add --global purescript@0.15.15 spago@latest
          bun install
          spago install

      - name: Build
        run: spago build

      - name: Test
        run: spago test